name: "📖 User Story"
description: "A high-level story that describes a user-facing feature or capability."
title: ""
labels: ["User Story"]

body:
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: What is the user story? What problem does it solve?
      placeholder: "As a <user>, I want <feature> so that <benefit>..."

  - type: textarea
    id: additional-info
    attributes:
      label: ℹ️ Additional Information (optional)
      description: Any additional context or notes related to this story.
      placeholder: |
        - Some additional information
        - ...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: List the requirements that must be met for this story to be complete.
      placeholder: |
        - [ ] Some acceptance criteria
        - [ ] ...
