name: "🛠️ Task"
description: "A smaller task that supports a story or epic."
title: "[Task]"
labels: ["Task"]

body:
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: What needs to be done? Provide enough detail for implementation.
      placeholder: "Implement X, update Y, fix Z..."
